### ISSUE TITLE
0.3.2 is not tagged in Github

### ISSUE THREAD

**Issue by AntonEvers** [yireo/Yireo_NewRelic2#1]
Hi,

0.3.2 is not tagged in github, but it does exist in the master branch. Please add the git tag to add it to https://packagist.org/packages/yireo/magento2-newrelic2.

https://github.com/yireo/Yireo_NewRelic2/commit/5cd0cd51b7c98a787e4fed0160a9b08f147db7a0

**Comment by jissereitsma** [comment]
Actually, this was almost like a dummy commit back then, because we usually increment IDs only right before releasing. To avoid confusion, version 0.3.2 is now released properly.

**Comment by AntonEvers** [comment]
Thanks @jissereitsma
